from datetime import datetime
from typing import Protocol

from prompt_dispatcher.domain.delivery import DeliveryResult
from prompt_dispatcher.domain.execution import Execution, ExecutionHistory, ExecutionResult


class ExecutionRepositoryPort(Protocol):
    def try_start(self, execution: Execution) -> bool: ...
    def complete(self, execution_id: str, result: ExecutionResult) -> None: ...
    def add_delivery(self, execution_id: str, result: DeliveryResult) -> None: ...
    def find_running(self, job_id: str) -> Execution | None: ...
    def recover_abandoned(self, older_than: datetime) -> int: ...
    def purge_before(self, older_than: datetime) -> int: ...
    def find_history(
        self, since: datetime, query: str = "", limit: int = 100
    ) -> tuple[ExecutionHistory, ...]: ...
    def get_history(self, execution_id: str) -> ExecutionHistory | None: ...
