from collections.abc import Callable
from typing import Protocol

from prompt_dispatcher.domain.job import Job


class SchedulerPort(Protocol):
    def register(self, job: Job, callback: Callable[[str], None]) -> None: ...
    def start(self) -> None: ...

    def clear(self) -> None: ...
    def shutdown(self) -> None: ...
    @property
    def running(self) -> bool: ...
